---
- name: GATHER INFORMATION FROM ROUTERS
  hosts: cisco
  connection: network_cli
  gather_facts: no
  
  tasks:
    - name: show interfaces
      ios_command:
        commands: show ip interface brief

        wait_for:
          - result[0] contains G

      register: print_output

    -  debug: var=print_output
